### ISSUE TITLE
Endpoints with id in body instead of as a parameter

### ISSUE THREAD

**Issue by DaruZero** [Systax-Technologies/backend#123]
As of now, the PATCH and DELETE request endpoint to update or delete an order are located in `orders/by-id/index.ts`.
Should we move them in `orders/$orderId.ts`?

**Comment by DaruZero** [comment]
Same thing with PATCH and DELETE request endpoint in `productInstances/index.ts`, should we move them in `productInstances/$productInstanceId.ts`?

**Comment by nullndr** [comment]
yes
